name: Process & Upload SARIF Results
description: Process & upload SARIF results

inputs:
  sarif_dir:
    description: Directory of CodeQL SARIF results output
    required: true
  filter_patterns:
    description: Comma-separated list of filter patterns
    required: false

runs:
  using: composite
  steps:
    - name: Set SARIF file
      shell: bash
      run: |
        sarif_dir=${{ inputs.sarif_dir }}
        sarif_file=$(find ${sarif_dir} -type f -name "*.sarif" | head -n 1)
        echo "SARIF_FILE=${sarif_file}" >> $GITHUB_ENV

    - name: Set Filter patterns
      if: ${{ inputs.filter_patterns != '' }}
      id: set-patterns
      shell: bash
      run: |
        echo "patterns<<EOF" >> $GITHUB_OUTPUT
        echo "${{ inputs.filter_patterns }}" | tr ',' '\n' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Filter SARIF
      if: ${{ inputs.filter_patterns != '' }}
      uses: advanced-security/filter-sarif@2da736ff05ef065cb2894ac6892e47b5eac2c3c0 # v1.1
      with:
        patterns: ${{ steps.set-patterns.outputs.patterns }}
        input: ${{ env.SARIF_FILE }}
        output: ${{ env.SARIF_FILE }}

    - name: Upload SARIF
      id: upload-sarif
      uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
      with:
        sarif_file: ${{ env.SARIF_FILE }}