name: Dependency Review

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  dependency-review:
    name: Dependency Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        if: github.event_name == 'pull_request'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  
      - name: Dependency review
        if: github.event_name == 'pull_request'       
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: critical
          fail-on-scopes: runtime
          comment-summary-in-pr: always
          show-openssf-scorecard: false
          license-check: false
          show-patched-versions: true
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 120

      - name: Update commit status
        if: always()
        uses: braintree/security-workflows/.github/actions/commit-status@main
        with:
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          description: ${{ job.status == 'success' && 'Dependency review completed successfully.' || 'Dependency review failed.' }}
          context: dependency-review